[project]
name = "imagetools"
version = "4.0.0"
description = "Collection of JPEG image management tools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-api-python-client>=2.179.0",
    "google-auth>=2.40.3",
    "google-auth-httplib2>=0.2.0",
    "google-auth-oauthlib>=1.2.2",
    "pyprojroot>=0.3.0",
    "pyqt6>=6.9.1",
]

[dependency-groups]
dev = [
    "pip>=25.2",
    "pytest>=8.4.1",
]
