[project]
name = "imagetools"
version = "4.0.0"
description = "Collection of JPEG image management tools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyprojroot>=0.3.0",
    "pyqt6>=6.9.1",
]

[dependency-groups]
dev = [
    "pip>=25.2",
    "pytest>=8.4.1",
]
