# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\python\imagetools\src\resources\uixml\import_images.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Import(object):
    def setupUi(self, Import):
        Import.setObjectName("Import")
        Import.resize(402, 526)
        self.gridLayout_4 = QtWidgets.QGridLayout(Import)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(Import)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Import)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radio_move = QtWidgets.QRadioButton(self.groupBox)
        self.radio_move.setChecked(False)
        self.radio_move.setObjectName("radio_move")
        self.gridLayout_3.addWidget(self.radio_move, 0, 0, 1, 1)
        self.radio_copy = QtWidgets.QRadioButton(self.groupBox)
        self.radio_copy.setChecked(True)
        self.radio_copy.setObjectName("radio_copy")
        self.gridLayout_3.addWidget(self.radio_copy, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Import)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.edit_destination = QtWidgets.QLineEdit(self.groupBox_2)
        self.edit_destination.setObjectName("edit_destination")
        self.gridLayout_2.addWidget(self.edit_destination, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.btn_import = QtWidgets.QPushButton(Import)
        self.btn_import.setObjectName("btn_import")
        self.gridLayout_4.addWidget(self.btn_import, 3, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Import)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 4, 0, 1, 1)
        self.text = QtWidgets.QTextBrowser(Import)
        self.text.setObjectName("text")
        self.gridLayout_4.addWidget(self.text, 5, 0, 1, 1)
        self.btn_goto = QtWidgets.QPushButton(Import)
        self.btn_goto.setObjectName("btn_goto")
        self.gridLayout_4.addWidget(self.btn_goto, 6, 0, 1, 1)

        self.retranslateUi(Import)
        QtCore.QMetaObject.connectSlotsByName(Import)

    def retranslateUi(self, Import):
        _translate = QtCore.QCoreApplication.translate
        Import.setWindowTitle(_translate("Import", "Import"))
        self.groupBox_3.setTitle(_translate("Import", "Note"))
        self.label.setText(_translate("Import", "This will include all .CR2 files..."))
        self.groupBox.setTitle(_translate("Import", "Preferences"))
        self.radio_move.setText(_translate("Import", "Move"))
        self.radio_copy.setText(_translate("Import", "Copy"))
        self.groupBox_2.setTitle(_translate("Import", "Destination: "))
        self.btn_import.setText(_translate("Import", "Import"))
        self.btn_goto.setText(_translate("Import", "Take me to the new folder..."))
