# Form implementation generated from reading ui file 'C:\dev\python\imagetools\src\ui\designer\created_to_mod.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_created_to_mod(object):
    def setupUi(self, created_to_mod):
        created_to_mod.setObjectName("created_to_mod")
        created_to_mod.resize(679, 739)
        self.verticalLayout = QtWidgets.QVBoxLayout(created_to_mod)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=created_to_mod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.text_documentation = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_documentation.sizePolicy().hasHeightForWidth())
        self.text_documentation.setSizePolicy(sizePolicy)
        self.text_documentation.setMinimumSize(QtCore.QSize(0, 25))
        self.text_documentation.setMaximumSize(QtCore.QSize(16777215, 110))
        self.text_documentation.setReadOnly(True)
        self.text_documentation.setObjectName("text_documentation")
        self.gridLayout.addWidget(self.text_documentation, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.rd_selected_files_only = QtWidgets.QRadioButton(parent=created_to_mod)
        self.rd_selected_files_only.setChecked(True)
        self.rd_selected_files_only.setObjectName("rd_selected_files_only")
        self.verticalLayout.addWidget(self.rd_selected_files_only)
        self.rd_entire_folder = QtWidgets.QRadioButton(parent=created_to_mod)
        self.rd_entire_folder.setObjectName("rd_entire_folder")
        self.verticalLayout.addWidget(self.rd_entire_folder)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=created_to_mod)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edit_folder_path = QtWidgets.QLineEdit(parent=created_to_mod)
        self.edit_folder_path.setObjectName("edit_folder_path")
        self.horizontalLayout_2.addWidget(self.edit_folder_path)
        self.btn_folder_select = QtWidgets.QPushButton(parent=created_to_mod)
        self.btn_folder_select.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_folder_select.setObjectName("btn_folder_select")
        self.horizontalLayout_2.addWidget(self.btn_folder_select)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btn_perform_action = QtWidgets.QPushButton(parent=created_to_mod)
        self.btn_perform_action.setObjectName("btn_perform_action")
        self.verticalLayout.addWidget(self.btn_perform_action)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=created_to_mod)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.text_output = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.text_output.setReadOnly(True)
        self.text_output.setObjectName("text_output")
        self.gridLayout_2.addWidget(self.text_output, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.progress_bar = QtWidgets.QProgressBar(parent=created_to_mod)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.btn_close_redirect = QtWidgets.QPushButton(parent=created_to_mod)
        self.btn_close_redirect.setObjectName("btn_close_redirect")
        self.verticalLayout.addWidget(self.btn_close_redirect)
        self.btn_close = QtWidgets.QPushButton(parent=created_to_mod)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close)

        self.retranslateUi(created_to_mod)
        self.btn_close.clicked.connect(created_to_mod.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(created_to_mod)

    def retranslateUi(self, created_to_mod):
        _translate = QtCore.QCoreApplication.translate
        created_to_mod.setWindowTitle(_translate("created_to_mod", "Created to Mod"))
        self.groupBox.setTitle(_translate("created_to_mod", "Documentation"))
        self.text_documentation.setPlainText(_translate("created_to_mod", "This operation helps you overwrite the append and modified time of all jpg files in a specified folder (non recursive) or for a given list of files with their created time. \n"
"\n"
"This is useful for ensuring that the modified time reflects the original creation time."))
        self.rd_selected_files_only.setText(_translate("created_to_mod", "Process selected files only"))
        self.rd_entire_folder.setText(_translate("created_to_mod", "Process entire folder (below)"))
        self.label_2.setText(_translate("created_to_mod", "Process folder path"))
        self.btn_folder_select.setText(_translate("created_to_mod", "..."))
        self.btn_perform_action.setText(_translate("created_to_mod", "Perform created_to_mod operation"))
        self.groupBox_2.setTitle(_translate("created_to_mod", "Output"))
        self.btn_close_redirect.setText(_translate("created_to_mod", "Close and go to output folder"))
        self.btn_close.setText(_translate("created_to_mod", "Close"))
