# Form implementation generated from reading ui file 'C:\dev\python\imagetools\src\ui\designer\flat_to_tree.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_flat_to_tree(object):
    def setupUi(self, flat_to_tree):
        flat_to_tree.setObjectName("flat_to_tree")
        flat_to_tree.resize(679, 739)
        self.verticalLayout = QtWidgets.QVBoxLayout(flat_to_tree)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=flat_to_tree)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.text_documentation = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_documentation.sizePolicy().hasHeightForWidth())
        self.text_documentation.setSizePolicy(sizePolicy)
        self.text_documentation.setMinimumSize(QtCore.QSize(0, 25))
        self.text_documentation.setMaximumSize(QtCore.QSize(16777215, 110))
        self.text_documentation.setReadOnly(True)
        self.text_documentation.setObjectName("text_documentation")
        self.gridLayout.addWidget(self.text_documentation, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=flat_to_tree)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edit_folder_path = QtWidgets.QLineEdit(parent=flat_to_tree)
        self.edit_folder_path.setObjectName("edit_folder_path")
        self.horizontalLayout_2.addWidget(self.edit_folder_path)
        self.btn_folder_select = QtWidgets.QPushButton(parent=flat_to_tree)
        self.btn_folder_select.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_folder_select.setObjectName("btn_folder_select")
        self.horizontalLayout_2.addWidget(self.btn_folder_select)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btn_perform_action = QtWidgets.QPushButton(parent=flat_to_tree)
        self.btn_perform_action.setObjectName("btn_perform_action")
        self.verticalLayout.addWidget(self.btn_perform_action)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=flat_to_tree)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.text_output = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.text_output.setReadOnly(True)
        self.text_output.setObjectName("text_output")
        self.gridLayout_2.addWidget(self.text_output, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.progress_bar = QtWidgets.QProgressBar(parent=flat_to_tree)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.btn_close_redirect = QtWidgets.QPushButton(parent=flat_to_tree)
        self.btn_close_redirect.setObjectName("btn_close_redirect")
        self.verticalLayout.addWidget(self.btn_close_redirect)
        self.btn_close = QtWidgets.QPushButton(parent=flat_to_tree)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close)

        self.retranslateUi(flat_to_tree)
        self.btn_close.clicked.connect(flat_to_tree.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(flat_to_tree)

    def retranslateUi(self, flat_to_tree):
        _translate = QtCore.QCoreApplication.translate
        flat_to_tree.setWindowTitle(_translate("flat_to_tree", "Flat to tree"))
        self.groupBox.setTitle(_translate("flat_to_tree", "Documentation"))
        self.text_documentation.setPlainText(_translate("flat_to_tree", "To structure images it is convenient to group them into folders by date.\n"
"This script will take all files in a folder and move them into subfolders named by their \'date modified\' (=mtime).\n"
"For date folders the ISO8601 format is used: YYYY-MM-DD."))
        self.label_2.setText(_translate("flat_to_tree", "Process folder path"))
        self.btn_folder_select.setText(_translate("flat_to_tree", "..."))
        self.btn_perform_action.setText(_translate("flat_to_tree", "Perform flat_to_tree operation"))
        self.groupBox_2.setTitle(_translate("flat_to_tree", "Output"))
        self.btn_close_redirect.setText(_translate("flat_to_tree", "Close and go to output folder"))
        self.btn_close.setText(_translate("flat_to_tree", "Close"))
