# Form implementation generated from reading ui file 'C:\dev\python\imagetools\src\ui\designer\heic_to_jpg.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_heic_to_jpg(object):
    def setupUi(self, heic_to_jpg):
        heic_to_jpg.setObjectName("heic_to_jpg")
        heic_to_jpg.resize(679, 739)
        self.verticalLayout = QtWidgets.QVBoxLayout(heic_to_jpg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=heic_to_jpg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.text_documentation = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_documentation.sizePolicy().hasHeightForWidth())
        self.text_documentation.setSizePolicy(sizePolicy)
        self.text_documentation.setMinimumSize(QtCore.QSize(0, 25))
        self.text_documentation.setMaximumSize(QtCore.QSize(16777215, 110))
        self.text_documentation.setReadOnly(True)
        self.text_documentation.setObjectName("text_documentation")
        self.gridLayout.addWidget(self.text_documentation, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=heic_to_jpg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edit_folder_path = QtWidgets.QLineEdit(parent=heic_to_jpg)
        self.edit_folder_path.setObjectName("edit_folder_path")
        self.horizontalLayout_2.addWidget(self.edit_folder_path)
        self.btn_folder_select = QtWidgets.QPushButton(parent=heic_to_jpg)
        self.btn_folder_select.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_folder_select.setObjectName("btn_folder_select")
        self.horizontalLayout_2.addWidget(self.btn_folder_select)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btn_perform_action = QtWidgets.QPushButton(parent=heic_to_jpg)
        self.btn_perform_action.setObjectName("btn_perform_action")
        self.verticalLayout.addWidget(self.btn_perform_action)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=heic_to_jpg)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.text_output = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.text_output.setReadOnly(True)
        self.text_output.setObjectName("text_output")
        self.gridLayout_2.addWidget(self.text_output, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.progress_bar = QtWidgets.QProgressBar(parent=heic_to_jpg)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.btn_close_redirect = QtWidgets.QPushButton(parent=heic_to_jpg)
        self.btn_close_redirect.setObjectName("btn_close_redirect")
        self.verticalLayout.addWidget(self.btn_close_redirect)
        self.btn_close = QtWidgets.QPushButton(parent=heic_to_jpg)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close)

        self.retranslateUi(heic_to_jpg)
        self.btn_close.clicked.connect(heic_to_jpg.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(heic_to_jpg)

    def retranslateUi(self, heic_to_jpg):
        _translate = QtCore.QCoreApplication.translate
        heic_to_jpg.setWindowTitle(_translate("heic_to_jpg", "HEIC to JPEG"))
        self.groupBox.setTitle(_translate("heic_to_jpg", "Documentation"))
        self.text_documentation.setPlainText(_translate("heic_to_jpg", "Iphone pictures are taken in .heic format, which is not supported by many applications.\n"
"This operation converts those .heic files into .jpg files while preserving the EXIF data and modified date.\n"
"It will also remove the original .heic files.\n"
"\n"
"Iphone live photos also come with an associated .mov or .mp4 file that have the same base name and nearly the same modified time. This operation will also remove those files."))
        self.label_2.setText(_translate("heic_to_jpg", "Process folder path"))
        self.btn_folder_select.setText(_translate("heic_to_jpg", "..."))
        self.btn_perform_action.setText(_translate("heic_to_jpg", "Perform heic to jpg operation"))
        self.groupBox_2.setTitle(_translate("heic_to_jpg", "Output"))
        self.btn_close_redirect.setText(_translate("heic_to_jpg", "Close and go to output folder"))
        self.btn_close.setText(_translate("heic_to_jpg", "Close"))
