# Form implementation generated from reading ui file 'C:\dev\python\imagetools\src\ui\designer\rename_auto.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_rename_auto(object):
    def setupUi(self, rename_auto):
        rename_auto.setObjectName("rename_auto")
        rename_auto.resize(679, 739)
        self.verticalLayout = QtWidgets.QVBoxLayout(rename_auto)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=rename_auto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.text_documentation = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_documentation.sizePolicy().hasHeightForWidth())
        self.text_documentation.setSizePolicy(sizePolicy)
        self.text_documentation.setMinimumSize(QtCore.QSize(0, 25))
        self.text_documentation.setMaximumSize(QtCore.QSize(16777215, 110))
        self.text_documentation.setReadOnly(True)
        self.text_documentation.setObjectName("text_documentation")
        self.gridLayout.addWidget(self.text_documentation, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.rd_selected_files_only = QtWidgets.QRadioButton(parent=rename_auto)
        self.rd_selected_files_only.setChecked(True)
        self.rd_selected_files_only.setObjectName("rd_selected_files_only")
        self.verticalLayout.addWidget(self.rd_selected_files_only)
        self.rd_entire_folder = QtWidgets.QRadioButton(parent=rename_auto)
        self.rd_entire_folder.setObjectName("rd_entire_folder")
        self.verticalLayout.addWidget(self.rd_entire_folder)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=rename_auto)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edit_folder_path = QtWidgets.QLineEdit(parent=rename_auto)
        self.edit_folder_path.setObjectName("edit_folder_path")
        self.horizontalLayout_2.addWidget(self.edit_folder_path)
        self.btn_folder_select = QtWidgets.QPushButton(parent=rename_auto)
        self.btn_folder_select.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_folder_select.setObjectName("btn_folder_select")
        self.horizontalLayout_2.addWidget(self.btn_folder_select)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=rename_auto)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.edit_template = QtWidgets.QLineEdit(parent=rename_auto)
        self.edit_template.setObjectName("edit_template")
        self.horizontalLayout.addWidget(self.edit_template)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_perform_action = QtWidgets.QPushButton(parent=rename_auto)
        self.btn_perform_action.setObjectName("btn_perform_action")
        self.verticalLayout.addWidget(self.btn_perform_action)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=rename_auto)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.text_output = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.text_output.setReadOnly(True)
        self.text_output.setObjectName("text_output")
        self.gridLayout_2.addWidget(self.text_output, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.progress_bar = QtWidgets.QProgressBar(parent=rename_auto)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.btn_close_redirect = QtWidgets.QPushButton(parent=rename_auto)
        self.btn_close_redirect.setObjectName("btn_close_redirect")
        self.verticalLayout.addWidget(self.btn_close_redirect)
        self.btn_close = QtWidgets.QPushButton(parent=rename_auto)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close)

        self.retranslateUi(rename_auto)
        self.btn_close.clicked.connect(rename_auto.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(rename_auto)

    def retranslateUi(self, rename_auto):
        _translate = QtCore.QCoreApplication.translate
        rename_auto.setWindowTitle(_translate("rename_auto", "Rename Auto"))
        self.groupBox.setTitle(_translate("rename_auto", "Documentation"))
        self.text_documentation.setPlainText(_translate("rename_auto", "This operations helps you rename all files in a specified folder in an automated way.\n"
"\n"
"The new file name is defined using a template string that can contain tags.\n"
"- you can add a sequence number based on the file name or the file modified time in different length using tags:\n"
"$seq_alpha_1, $seq_alpha_2, $seq_alpha_3 ,$seq_alpha_4, $seq_alpha_5\n"
"$seq_mtime_1, $seq_mtime_2, $seq_mtime_3 ,$seq_mtime_4, $seq_mtime_5\n"
"\n"
"- you can add the file name without extension using the tag $name\n"
"\n"
"- you can different representation of the mtime:\n"
"$mtime_date gives you the modified time as yyyymmdd\n"
"$mtime_date_sep gives you the modified time as yyyy-mm-dd\n"
"- you can different representation of the mtime:\n"
"$mtime_time gives you the modified time as hhmmss\n"
"$mtime_time_sep gives you the modified time as hh-mm-ss\n"
"\n"
"\n"
"- you can add the file extension using the tag $ext\n"
"\n"
"- you can add a fixed piece of text anywhere in the new template without using any tags, just write it as is."))
        self.rd_selected_files_only.setText(_translate("rename_auto", "Process selected files only"))
        self.rd_entire_folder.setText(_translate("rename_auto", "Process entire folder (below)"))
        self.label_2.setText(_translate("rename_auto", "Process folder path"))
        self.btn_folder_select.setText(_translate("rename_auto", "..."))
        self.label_3.setText(_translate("rename_auto", "Template"))
        self.edit_template.setText(_translate("rename_auto", " $seq_mtime_3-$mtime_dateT$mtime_time_-$name$ext"))
        self.btn_perform_action.setText(_translate("rename_auto", "Perform rename_auto operation"))
        self.groupBox_2.setTitle(_translate("rename_auto", "Output"))
        self.btn_close_redirect.setText(_translate("rename_auto", "Close and go to output folder"))
        self.btn_close.setText(_translate("rename_auto", "Close"))
