# Form implementation generated from reading ui file 'C:\dev\python\imagetools\src\ui\designer\takeout.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_takeout(object):
    def setupUi(self, takeout):
        takeout.setObjectName("takeout")
        takeout.resize(679, 739)
        self.verticalLayout = QtWidgets.QVBoxLayout(takeout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=takeout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.text_documentation = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_documentation.sizePolicy().hasHeightForWidth())
        self.text_documentation.setSizePolicy(sizePolicy)
        self.text_documentation.setMinimumSize(QtCore.QSize(0, 25))
        self.text_documentation.setMaximumSize(QtCore.QSize(16777215, 110))
        self.text_documentation.setReadOnly(True)
        self.text_documentation.setObjectName("text_documentation")
        self.gridLayout.addWidget(self.text_documentation, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=takeout)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edit_input_path = QtWidgets.QLineEdit(parent=takeout)
        self.edit_input_path.setObjectName("edit_input_path")
        self.horizontalLayout.addWidget(self.edit_input_path)
        self.btn_input_select = QtWidgets.QPushButton(parent=takeout)
        self.btn_input_select.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_input_select.setObjectName("btn_input_select")
        self.horizontalLayout.addWidget(self.btn_input_select)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=takeout)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edit_output_path = QtWidgets.QLineEdit(parent=takeout)
        self.edit_output_path.setObjectName("edit_output_path")
        self.horizontalLayout_2.addWidget(self.edit_output_path)
        self.btn_output_select = QtWidgets.QPushButton(parent=takeout)
        self.btn_output_select.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_output_select.setObjectName("btn_output_select")
        self.horizontalLayout_2.addWidget(self.btn_output_select)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btn_takeout = QtWidgets.QPushButton(parent=takeout)
        self.btn_takeout.setObjectName("btn_takeout")
        self.verticalLayout.addWidget(self.btn_takeout)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=takeout)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.text_output = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.text_output.setObjectName("text_output")
        self.gridLayout_2.addWidget(self.text_output, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.progress_bar = QtWidgets.QProgressBar(parent=takeout)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.btn_close_redirect = QtWidgets.QPushButton(parent=takeout)
        self.btn_close_redirect.setObjectName("btn_close_redirect")
        self.verticalLayout.addWidget(self.btn_close_redirect)
        self.btn_close = QtWidgets.QPushButton(parent=takeout)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close)

        self.retranslateUi(takeout)
        self.btn_close.clicked.connect(takeout.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(takeout)

    def retranslateUi(self, takeout):
        _translate = QtCore.QCoreApplication.translate
        takeout.setWindowTitle(_translate("takeout", "Takeout"))
        self.groupBox.setTitle(_translate("takeout", "Documentation"))
        self.text_documentation.setPlainText(_translate("takeout", "Google photo users can download a takeout archive of their pictures as a single zip file.\n"
"Downloaded files have their \'mtime\' modified by google to the time of download which isn\'t useful for organizing pictures.\n"
"Luckily these takeout archives contain a .json file for each picture with the original metadata.\n"
"This operation allows you transform that zipfile into a folder of picture with \'mtime\' adapted using that json metadata."))
        self.label.setText(_translate("takeout", "Takeout zipfile or folder"))
        self.btn_input_select.setText(_translate("takeout", "..."))
        self.label_2.setText(_translate("takeout", "Output folder path"))
        self.btn_output_select.setText(_translate("takeout", "..."))
        self.btn_takeout.setText(_translate("takeout", "Perform takeout operation"))
        self.groupBox_2.setTitle(_translate("takeout", "Output"))
        self.btn_close_redirect.setText(_translate("takeout", "Close and go to output folder"))
        self.btn_close.setText(_translate("takeout", "Close"))
