# Form implementation generated from reading ui file 'C:\dev\python\imagetools\src\ui\designer\web_album.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_web_album(object):
    def setupUi(self, web_album):
        web_album.setObjectName("web_album")
        web_album.resize(312, 280)
        self.gridLayout = QtWidgets.QGridLayout(web_album)
        self.gridLayout.setObjectName("gridLayout")
        self.edit_title = QtWidgets.QLineEdit(parent=web_album)
        self.edit_title.setObjectName("edit_title")
        self.gridLayout.addWidget(self.edit_title, 0, 1, 1, 1)
        self.edit_location = QtWidgets.QLineEdit(parent=web_album)
        self.edit_location.setObjectName("edit_location")
        self.gridLayout.addWidget(self.edit_location, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=web_album)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.edit_description = QtWidgets.QLineEdit(parent=web_album)
        self.edit_description.setObjectName("edit_description")
        self.gridLayout.addWidget(self.edit_description, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=web_album)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=web_album)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btn_create = QtWidgets.QPushButton(parent=web_album)
        self.btn_create.setObjectName("btn_create")
        self.gridLayout.addWidget(self.btn_create, 3, 0, 1, 2)
        self.btn_cancel = QtWidgets.QPushButton(parent=web_album)
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 4, 0, 1, 2)
        self.progress_bar = QtWidgets.QProgressBar(parent=web_album)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progress_bar.setTextVisible(True)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout.addWidget(self.progress_bar, 5, 0, 1, 2)
        self.text_box = QtWidgets.QTextBrowser(parent=web_album)
        self.text_box.setObjectName("text_box")
        self.gridLayout.addWidget(self.text_box, 6, 0, 1, 2)

        self.retranslateUi(web_album)
        QtCore.QMetaObject.connectSlotsByName(web_album)
        web_album.setTabOrder(self.edit_title, self.edit_description)
        web_album.setTabOrder(self.edit_description, self.edit_location)
        web_album.setTabOrder(self.edit_location, self.btn_create)
        web_album.setTabOrder(self.btn_create, self.btn_cancel)
        web_album.setTabOrder(self.btn_cancel, self.text_box)

    def retranslateUi(self, web_album):
        _translate = QtCore.QCoreApplication.translate
        web_album.setWindowTitle(_translate("web_album", "Web Album Generator"))
        self.label_3.setText(_translate("web_album", "Location"))
        self.label_2.setText(_translate("web_album", "Album Description"))
        self.label.setText(_translate("web_album", "Album Title"))
        self.btn_create.setText(_translate("web_album", "Create webalbum"))
        self.btn_cancel.setText(_translate("web_album", "Cancel"))
